import{S as m,i as c}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const p=document.querySelector("input");p.value.trim();function f(s){const t=`https://pixabay.com/api/?${new URLSearchParams({key:"43082908-d5bb253eb19cb17ad501330a7",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(t).then(i=>{if(!i.ok)throw new Error(i.status);return i.json()})}const d=document.querySelector(".gallery"),h=document.querySelector("input");function g(s){if(s.length==0)c.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const o=s.map(t=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${t.largeImageURL}">
        <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
        </ul>
        </li>`).join("");d.insertAdjacentHTML("beforeend",o),y.refresh(),h.value=""}}const y=new m(".gallery a",{}),L=document.querySelector(".gallery");let n;const l=document.querySelector("input"),b=document.querySelector("form"),u=document.querySelector(".loader");function S(){u.classList.remove("is-hidden")}function q(){u.classList.add("is-hidden")}l.addEventListener("input",s=>{s.preventDefault(),n=l.value.trim()});b.addEventListener("submit",s=>{s.preventDefault(),S(),n===""&&c.error({color:"yellow",message:" Please fill in the field for search",position:"topRight"}),n&&f(n).then(o=>g(o.hits)).catch(o=>{console.log(o),c.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}).finally(()=>q()),L.innerHTML=""});
//# sourceMappingURL=commonHelpers.js.map
